### PR TITLE
Sass support

### PR DESCRIPTION
**Pull request by sshulin**
- installed "node-sass" and "sass-loader" to devDependencies
- added sass rule to webpack config, 
- added .scss to watchable extension list in package.json

### CODE REVIEW

**Comment by satendra02** [comment]
Hey @sshulin 

Thanks for your contribution. 

PR looks good. I will test these changes on my side and then merge it to the master.

**Comment by sshulin** [comment]
I use npm, so there's package-lock.json. If you want to sustain your project yarn only I could delete package-lock.json file and add new yarn.lock.

**Comment by satendra02** [comment]
Yes, delete the _package-lock.json_ file, and no need to add _yarn.lock_ file just remove the caret(^) symbol from the newly added packages inside _package.json_. So when someone runs the **install** command, the lock file will auto-update with the mentioned version at their end.

What are your thoughts?

**Comment by sshulin** [comment]
I've deleted package-lock.json, but I think it would be better to add updated yarn.lock file instead of just specifying versions of packages with exact match instead of "comatible with" option.

1. Every devDepency is specified with "compatible with" (^) version range and specifying part of them in a different manner would make devDependencies object look inconsistent
2. yarn.lock specifies exact version of package anyway
3. yarn.lock isn't added to .gitignore, so every user after this commit and executing yarn install will have to deal with updated yarn.lock file. I guess it will be better to keep everybody away from this problem

I'll push new yarn.lock or updated package.json after your answer. But I hope you are ok with my option

**Comment by satendra02** [comment]
Great! You are right we must add new _yarn.lock_.

**Comment by satendra02** [comment]
One more thing. This repo is a boilerplate to create a chrome extension using reactJS. 

So is it a good idea to make SASS as a part of the repo? 

Suppose if someone wants to use LESS for their styling then, should we make our repo compatible to LESS as well. If yes, then he has to unnecessarily install the SASS supported packages as well which will increase the bundle size somehow.

So Instead of adding it to the repo, we can create [Wiki](https://github.com/satendra02/react-chrome-extension/wiki) with the implementation details and mention these wikis in the _Readme.md_ file.

What do you say?

**Comment by sshulin** [comment]
We use those two packages only for build purposes, not in browser, so none of them get to our final production build. The worst thing that could be in our case - unnecessary packages in node_modules. Futhermore, **using sass by default even slightly reduces build size** - styles, written in sass compile to build minified. And if for some reason developer wants to use pure css - he can rename App.scss to App.css, import it as pure css and everything would be like it is now in master. 

As for other css preprocessors:
As we see, there's already issue about SASS, so we can do boilerplate better just by making webpack script able to compile SASS.   **Two options are better than no option**, afterall. And if someone would like to use LESS, Stylus or any other less common preprocessor they could fork this repo and replace sass-loader with any other loader.

**Comment by satendra02** [comment]
Yes right, build size is not going to be an issue. 

We can keep pure css as default and if someone wants to use _scss_ they can rename _App.css_ to _App.scss_. I think this is much better. Also need to update _Readme.md_ to make things clear.

**Comment by sshulin** [comment]
Done both using pure CSS by default and using SASS guide in _README.md_

**Pull request merged**
